記事追加: コマンドを入力した後のユーザーのメッセージを待機する方法【discord.py】
DiscordBotPortalJP/discordbot.jp pull request #17
Opened 2021-04-27 23:22 UTC by yutarou12

参考チャンネル
メッセージ待機 : 641486380505104424
記述式のクイズbot : 656856351435259935

2021-04-28 01:17 UTC, sizumita requested changes

2021-04-28 01:17 UTC, sizumita commented on content/blog/13.md
> +`wait_for` はメッセージイベントだけでなく、リアクションが追加されたときなどのイベントにも応用することが出来ますので、知っておくとよいものです。
くどいと思います

2021-04-28 01:17 UTC, sizumita commented on content/blog/13.md
> +            # メンション付きでメッセージを送信する。
メンションになってないと思います

2021-04-29 12:57 UTC, 1ntegrale9 commented on content/blog/13.md
> +            await channel.send(f'{msg.author.mention}さん、時間切れです')
ここはmsg変数への代入が失敗してるところなのでこうかな

```suggestion
        except asyncio.TimeoutError:
            await channel.send(f'{message.author.mention}さん、時間切れです')
```

2021-04-29 13:10 UTC, yutarou12 commented on content/blog/13.md
> +            await channel.send(f'{msg.author.mention}さん、時間切れです')
確かにエラー発生時こけますね....気を付けます

2021-04-29 23:17 UTC, 1ntegrale9 approved these changes
LGTM

2021-04-29 23:17 UTC, merged