記事追加: BOTが起動したときに、BOTのステータスを変更する【discord.py】
DiscordBotPortalJP/discordbot.jp pull request #23
Opened 2021-06-01 14:04 UTC by yutarou12

参考チャンネル
602035361262338049 (ステータスの変更方法)
713419299531915334 (プレイステータスを変更する方法)

必要性ないと感じたら、closeしてもらって構いません()

2021-06-01 19:45 UTC, sevenc-nanashi requested changes

2021-06-01 19:45 UTC, sevenc-nanashi commented on content/blog/15.md
> +起動時に、BOTのステータス欄に導入されているサーバー数などを表示させたい時に使えます。
ここにこうやって書いてるから鯖数を更新するとこまで書いたら長さ的にちょうどいい気がする

2021-06-02 13:16 UTC, sevenc-nanashi approved these changes

2021-06-02 13:46 UTC, grarich123 approved these changes

2021-06-17 16:29 UTC, 1ntegrale9 approved these changes
LGTM

2021-06-17 16:29 UTC, merged