記事追加: なぜcommandsフレームワークを使うときはon_messageに注意しなければいけないのか
DiscordBotPortalJP/discordbot.jp pull request #28
Opened 2021-06-18 13:45 UTC by daima3629

2021-06-18 14:19 UTC, sevenc-nanashi requested changes, later dismissed

2021-06-18 14:19 UTC, sevenc-nanashi commented on content/blog/17.md
> +- [commands.Cog.listener](https://discordpy.readthedocs.io/ja/latest/ext/commands/api.html#discord.ext.commands.Cog.listener)
```suggestion
- [Bot.event](https://discordpy.readthedocs.io/ja/stable/ext/commands/api.html#discord.ext.commands.Bot.event)
- [Bot.process_commands](https://discordpy.readthedocs.io/ja/stable/ext/commands/api.html#discord.ext.commands.Bot.process_commands)
- [Bot.listen](https://discordpy.readthedocs.io/ja/stable/ext/commands/api.html#discord.ext.commands.Bot.listen)
- [commands.Cog.listener](https://discordpy.readthedocs.io/ja/stable/ext/commands/api.html#discord.ext.commands.Cog.listener)
```

安定版のリンクの方が良いのでは？
また、bot.eventも必要だと思います。

2021-06-18 14:25 UTC, daima3629 commented on content/blog/17.md
> +- [commands.Cog.listener](https://discordpy.readthedocs.io/ja/latest/ext/commands/api.html#discord.ext.commands.Cog.listener)
あー、確かに
R.Dannyで出てきたリンクをそのまま使ってました
Bot.eventもそうですね、ご指摘ありがとうございます

2021-06-18 14:34 UTC, 1ntegrale9 commented on content/blog/17.md
> +title: なぜcommandsフレームワークを使うときはon_messageに注意しなければいけないのか
一応タイトルで discord.py というのが分かった方が良いかな

```suggestion
title: なぜcommandsフレームワークを使うときはon_messageに注意しなければいけないのか【discord.py】
```

2021-06-18 14:35 UTC, 1ntegrale9 commented
あと master にフォント更新が反映されたので取り込んで確認していただければと思います〜

2021-06-18 14:36 UTC, daima3629 commented on content/blog/17.md
> +title: なぜcommandsフレームワークを使うときはon_messageに注意しなければいけないのか
確かにそうですね、ご指摘ありがとうございます！

2021-06-18 14:37 UTC, daima3629 commented
えーっとどう取り込めばいいんでしたっけ…
カレントブランチがこのブランチの状態で`git merge master` すればいいんでしたっけ？

2021-06-18 14:40 UTC, daima3629 commented
chunさんのおかげで無事取り込めました！

2021-06-18 17:20 UTC, daima3629 commented
サンプルコードを`samplecode/`に入れるのを忘れていました…
今日の昼に入れます

2021-06-19 05:16 UTC, daima3629 commented
入れました

2021-06-19 05:17 UTC, sevenc-nanashi approved these changes
ここだけなおしたらlgtm

2021-06-19 05:17 UTC, sevenc-nanashi commented on samplecode/blog17.py
> +#対策2(関数名変更ver)
```suggestion
# 対策2(関数名変更ver)
```
空白ないのが地味に気になる

2021-06-19 05:18 UTC, daima3629 commented on samplecode/blog17.py
> +#対策2(関数名変更ver)
おぅふ
指摘ありがとうございます

2021-06-19 06:21 UTC, yutarou12 approved these changes
LGTM

2021-06-19 08:18 UTC, merged